appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: 5DkoPmQpaslUlCXrswzVxoK6AFzhc0biIJRD8B70CaloH5jH08zvOJr2Z1dDFVpQa7sTm6snxHV1ZUdrAyxCF4RNnF1mBzHvVZ9V1kB0YBDCgEBS7yvIpKoOYGeHIyNnksOdQSfbRvcUxS4mvhStcM6ta/MsLo3olZJmToUEliMCqcVYyX+9bjO9dolbtoROaTM7SYklcNewWXIHDdixXMdMW7o2BSS5fXtUrtIi+5wWuFp36djniZg8QqTIK8QK7ap9EyEGtPvVAL2bWsbS2PS3lTrJHY8ZYH12k3+ZmB24QQfg822ng2V6eTnADGFXOMC5YdRllXzmA+u7ZkpZSm7ZQ4LRA2okub4NSrHW+yNoxRaFYI/F/QXqVfZjBK8FyMaZDfCRPErWagyZVaZqWlNXnwLiUlCr5DQXq8ov0xJe0/s0Pm7sS/orYzM1PCVc3NJNlWbf1GKMjy8kL3MngGYMBsv3Vz2NKZvWioEM897w54VN2ILRRVfZy3++GklssFkySQWQBtLQKWVwNeMZ+xxFai9XDFx5X9i1s5wrsqmRGG4rnS04xVtSLr3NBoWSOX/WGdCNDcVekq48kTf1RigavvIwqrIx+CCwOkPf9rTqU2CWKghc0PMiQAJViO4YqENY55k1e+PBXTffD+BRFjBcMShYacunt2YrzPt3Ij8=}
